# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # points to the latest development branch e.g. 3.6-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
  - "DOWNLOAD THE RELEVANT API DEFINITION"
  - cp /Users/ethankeller/onshape/api-generator/api_data/onshape_openapi_spec.yaml /Users/ethankeller/onshape/api-generator/swagger_clients/onshape_python_sdk
#  Turn the operationIds into more manageable client names
  - "perl -pi -w -e 's/(operationId: \w*)\.\w*/$1/;' onshape_openapi_spec.yaml"
#  Generate the API client
  - "swagger-codegen generate -i onshape_openapi_spec.yaml -l python -o . -c swagger_config.json"
# Replace the import statements that are screwed up
  - cd onshape_client/models
  - "perl -pi -w -e 's/(from [a-z_.0-9]*)1\b/$1_1/;' [^__init__.py]*"
  - TEST THE CLIENT
