language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
before_install:
  #  parse the build_type into a variable
  - build_type="$(echo $TRAVIS_COMMIT_MESSAGE | ack -o '(?<=build_type:)\w+')"
  - "echo 'the build type is: ${build_type}'"
  - openssl aes-256-cbc -K $encrypted_748edd81b0f1_key -iv $encrypted_748edd81b0f1_iv
    -in .onshape_client_config.yaml.enc -out .onshape_client_config.yaml -d
  - ".travis/generate_client.sh"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - build_type="$(echo $TRAVIS_COMMIT_MESSAGE | ack -o '(?<=build_type:)\w+')"
  - pipenv run pytest --cov=./
  - |
    if [ "$build_type" = "swagger_build" ]; then
      .travis/git_push.sh -t $TRAVIS_BUILD_NUMBER -n "An automated Travis release build_type:swagger_build"
    fi"
deploy:
  provider: pypi
  user: ethan92492
  password:
    secure: VrvP9Gml6iZ8gogaKRqpasx0XTIouH54tP7mLU9mub5sVYmpOCYOwAlWoEp2gesthyww40UiFb2fE6C/T0uzDOfivRcdsn5As1R+n+i0ZE26HyGdn13uBSp/kKQy1xHUQGc7xf7Ri3RmiePiR2piLhHnC/KQygVZzzRfO3HiRrt43dci/8QY7vsZi2sdqmzraZ69M/coVq+tfwWYyLkPbLfwwQBfSlTXG/HCwdp0A4l3e+m+YWzWmFG5/vntwRMkNUPbBLKFokj1MlNRDhn+gdymneDShedub1Ggm8zG7d88yNH+lq9UpmSOKd6SqNOrDosX/R/J6DAqYr40qo8MbwuY142vObU/CRtN52f+Sm5xjV9lA1LX9V9oTye2WKBD+3205h1+TO0m5dlOvxlVNAk4eWS2seEV2rtUD3H2YH1xVDEom7Ynfk9yDcREgkPsXEtL24rIcq+aY7DUNhidk0Pm6jxGhPR4AcKbXU9lxyP2H6N/T7cRoFkAhZaFttalAALbs3ESZHKg6oCol5nKJ6bPCAk7+DY4WTn4xXG0YsXOa+ggz+iO49JItYreIWZccb7KPW/b4P68NbQQNs/s/3MNJwUYzkDRWeeNnZdXNHfQWe38S1DrvOBqKy2d5YNw+jXNr1yRe3BfqH7hYlVD3AxiQ/jWjeXAFVLSjqGfCsM=
  on:
    tags: true
  server: https://test.pypi.org/
env:
  global:
    secure: GM3yNK/W5PeoB2gLCTyY9AEG0fbUK3njvd+J/2r1EhJoel5kp+SpinNmV1+248JRgzn4I8m6pNeekSWA/vMsjqvgqDq2CPEwY4P+T4TLL8+3HW03wJ7xNDEVHpMVbplvkh0x4YyssDRU+Q4xswAzaiG40uHRVLAG1EN03UcdLIMo66fHkd5/dYz+FnJJb+MkcVOkrfXu3WRxxkDKBGoIzKjZDJT1r8/eR7dELjFpj1gBYy1M2tjev65NUA7zgMvaMIiFed2W3SrvF7+XUkNNWF/rX17P3JsUf6UD5rhJswS2mKed2GwVq2VxDmxJRDwDx5aahIo+MtA6c3DkZIW6qoYiFVV7kJF4ziH7BjapoG6Gag/wc7YiVLAGv9dsqpGvlb9S+6xUjdV1jdAyWnBgciuomjf+bbmU1LHNBHUltAzjMIvLVEhhDR8r7GlQ53QZZ9Tw9Da8+sPLIhUBnt+Tm1B79cHOfG+J/GKiICNmUOGKqlQT8FZhOkziZHY+TcBCcY5up0Uxz99gGqTnYB7YZtyaB1HqGVpjJT4xEEzhGmaWmArVr4IdcSoMVn3F8ES3OaDw7kMbhFltKhsfUjZz1m8LilRk9nq/69yneeRP9ZYZm0A0a6+HDbYztEge+aVICC0tr/1fxTfzcGX13By2So3lbffGrhTf9BmegIClKeo=
