matrix:
  include:
    - language: python
      python: 3.7
      before_script:
        - cd python
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run pytest
