prod-api_keys:
  baseUrl: "https://cad.onshape.com"
  secret_key: YOUR SECRET KEY
  access_key: YOUR ACCESS KEY
prod-oauth:
  baseUrl: "https://cad.onshape.com"
  # Make sure to include handling authentication errors by using the refreshToken as discussed here
  # under OAuth => Refreshing the access token: https://dev-portal.onshape.com/help
  access_token: YOU OAUTH ACCESS TOKEN
default: prod-oauth