prod-api_keys:
  base_url: "https://cad.onshape.com"
  secret_key: YOUR SECRET KEY
  access_key: YOUR ACCESS KEY
prod-oauth:
  base_url: "https://cad.onshape.com"
  # Make sure to include handling authentication errors by using the refreshToken as discussed here
  # under OAuth => Refreshing the access token: https://dev-portal.onshape.com/help
  # access_token: <OPTIONAL> YOU OAUTH ACCESS TOKEN
  client_id: IZ3....
  client_secret: GZE2.....
  redirect_uri: http://localhost:9000
  token_uri: https://oauth.onshape.com/oauth/token
  authorization_uri: https://oauth.onshape.com/oauth/authorize
  scope:
   - OAuth2Read
   - OAuth2Write
  #  refresh_token: <OPTIONAL>
  oauth_authorization_method: localhost_server
default_stack: prod-oauth
